//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterClient.RegisterClientProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegisterClientProxy.IRegisterClientService")]
    public interface IRegisterClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterClientService/RegisterUser", ReplyAction="http://tempuri.org/IRegisterClientService/RegisterUserResponse")]
        string RegisterUser(string name, string email, string mobilephonenumber, string phonenumber, string birthdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterClientService/RegisterUser", ReplyAction="http://tempuri.org/IRegisterClientService/RegisterUserResponse")]
        System.Threading.Tasks.Task<string> RegisterUserAsync(string name, string email, string mobilephonenumber, string phonenumber, string birthdate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterClientServiceChannel : RegisterClient.RegisterClientProxy.IRegisterClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterClientServiceClient : System.ServiceModel.ClientBase<RegisterClient.RegisterClientProxy.IRegisterClientService>, RegisterClient.RegisterClientProxy.IRegisterClientService {
        
        public RegisterClientServiceClient() {
        }
        
        public RegisterClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegisterUser(string name, string email, string mobilephonenumber, string phonenumber, string birthdate) {
            return base.Channel.RegisterUser(name, email, mobilephonenumber, phonenumber, birthdate);
        }
        
        public System.Threading.Tasks.Task<string> RegisterUserAsync(string name, string email, string mobilephonenumber, string phonenumber, string birthdate) {
            return base.Channel.RegisterUserAsync(name, email, mobilephonenumber, phonenumber, birthdate);
        }
    }
}
